---
apiVersion: v1
kind: Namespace
metadata:
  name: leadeasygen-nodeserv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-api
  namespace: leadeasygen-nodeserv
  labels:
    app: ms-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-api
  template:
    metadata:
      labels:
        app: ms-api
    spec:
      containers:
        - name: ms-api
          image: choleski/ms-api:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 4002
          env:
          # App
          - name: APP_VERSION
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: app_version
          - name: APP_NAME
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: app_name
          - name: APP_SERVICE
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: app_service
          - name: APP_HOST
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: app_host
          - name: APP_CLIENT_HOST
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: app_client_host
          - name: APP_SHUTDOWN
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: app_shutdown
          # Api
          - name: API_BASE_URL
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: api_base_url
          # Node
          - name: NODE_ENV
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: node_env
          - name: NODE_PORT
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: node_port
          # Postgres
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: api-root-username
          - name: POSTGRES_PASS
            valueFrom: 
              secretKeyRef:
                name: api-secret
                key: api-root-password
          - name: POSTGRES_HOST
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: database_host
          - name: POSTGRES_PORT
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: database_port
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: database_name
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ms-api
  namespace: leadeasygen-nodeserv
spec:
  selector:
    app: ms-api
  ports:
  - protocol: TCP
    port: 3000
