---
apiVersion: v1
kind: Namespace
metadata:
  name: crypolio-nodeserv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-markets
  namespace: crypolio-nodeserv
  labels:
    app: ms-markets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-markets
  template:
    metadata:
      labels:
        app: ms-markets
    spec:
      containers:
        - name: ms-markets
          image: choleski/ms-markets:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 4002
          env:
          # App
          - name: APP_VERSION
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: app_version
          - name: APP_NAME
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: app_name
          - name: APP_SERVICE
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: app_service
          - name: APP_HOST
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: app_host
          - name: APP_CLIENT_HOST
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: app_client_host
          - name: APP_SHUTDOWN
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: app_shutdown
          # Api
          - name: API_BASE_URL
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: api_base_url
          # Node
          - name: NODE_ENV
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: node_env
          - name: NODE_PORT
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: node_port
          # JWT
          - name: JWT_ALGO
            valueFrom:
              secretKeyRef:
                name: markets-secret
                key: markets-jwt-algo
          - name: JWT_EXPIRY
            valueFrom:
              secretKeyRef:
                name: markets-secret
                key: markets-jwt-expiry
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: markets-secret
                key: markets-jwt-secret
          # Postgres
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: markets-secret
                key: markets-root-username
          - name: POSTGRES_PASS
            valueFrom: 
              secretKeyRef:
                name: markets-secret
                key: markets-root-password
          - name: POSTGRES_HOST
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: database_host
          - name: POSTGRES_PORT
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: database_port
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: database_name
          # Kafka
          - name: KAFKA_HOST
            valueFrom: 
              configMapKeyRef:
                name: markets-configmap
                key: kafka_host
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ms-markets
  namespace: crypolio-nodeserv
spec:
  selector:
    app: ms-markets
  ports:
  - protocol: TCP
    port: 4002
