version: '3.7'

networks:
  leadeadygen-net:
    external: true

services:
  ms-markets:
    user: node
    restart: always
    hostname: ms-markets
    container_name: ms-markets
    build:
      context: .
    volumes:
      - ./:/home/node:cached
    # extra_hosts:
    networks:
      - leadeadygen-net
    env_file:
      - .env
    environment:
      - APP_VERSION=${APP_VERSION}
      - APP_NAME=${APP_NAME}
      - APP_SERVICE=${APP_SERVICE}
      - APP_HOST=${APP_HOST}
      - APP_CLIENT_HOST=${APP_CLIENT_HOST}
      - APP_SHUTDOWN=${APP_SHUTDOWN}
 
      - NODE_PORT=${NODE_PORT}
      - NODE_ENV=${NODE_ENV}

      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - 3000:3000
      - 7000:7000
    expose:
      - 3000
      - 7000
